version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/
permissions:
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 6000
      runas: ec2-user

  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 6000
      runas: ec2-user
 
  ApplicationStart:
      - location: scripts/start_server
        timeout: 6000
        runas: ec2-user


  

